version: 2
updates:
- package-ecosystem: pip
  directory: "lib/metric-config-parser"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: pip
  directory: /.script
  schedule:
    interval: daily

- package-ecosystem: pip
  directory: /lib/metric-config-parser
  schedule:
    interval: daily
