name: "Auto approve"
on:
  pull_request:
    branches:
      - main

jobs:
  changed:
    uses: ./.github/workflows/changed-files.yml
    with:
      path_filter: |
        definitions/*.toml
        lib/
        .github/
        .circleci/

  approve:
    name: Auto approve PR if no metrics definitions changed
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest 
    needs: changed
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      if: needs.changed.outputs.any_changed == 'false'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: "APPROVE"
          })
    - name: Skip
      if: needs.changed.outputs.any_changed == 'true'
      run: |
        echo "Metric definitions changed, needs manual review"
        echo "Changed files: ${{ needs.changed.outputs.all_changed_files }}"

