name: "Build docs"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Setup python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python3.10 -m venv venv/
        venv/bin/python -m pip install -r .script/requirements.txt
        venv/bin/python -m pip install lib/metric-config-parser
    - name: Build docs
      run: |
        venv/bin/python .script/generate_docs.py \
          --output_dir=generated_docs/
        cd generated_docs/
        PATH="../venv/bin:$PATH" mkdocs gh-deploy --force \
          -m "[ci skip] Deployed {sha} with MkDocs version: {version}"
