name: Get changed files

on:
  workflow_call:
    inputs:
      path_filter:
        type: string
        description: 'Path filter to look for changed files'
        required: false
        default: '**'
    outputs:
      any_changed:
        description: 'Did any file matching optional path filter change? [true|false]'
        value: ${{ jobs.changed.outputs.any_changed }}
      all_changed_files:
        description: 'List of changed files matching optional path filter'
        value: ${{ jobs.changed.outputs.all_changed_files }}

jobs:
  changed:
    runs-on: ubuntu-latest 
    name: Get changed files
    outputs:
      any_changed: ${{ steps.changed-files-specific.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files-specific.outputs.all_changed_files }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
      with:
        files: ${{ inputs.path_filter }}
    - name: Print results
      run: |
        echo "Using path filter: ${{ inputs.path_filter }}"
        echo "Did files change?: ${{ steps.changed-files-specific.outputs.any_changed }}"
        echo "All changed files: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
