name: "Validate Looker"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'looker/**'
  push:
    branches:
      - main
    paths:
      - 'looker/**'

jobs:
  changed:
    uses: ./.github/workflows/changed-files.yml
    with:
      path_filter: |
        looker/**/*.toml
        looker/**/*.toml.example

  validate-looker:
    runs-on: ubuntu-latest
    needs: changed
    permissions:
      id-token: write
      contents: read
    if: needs.changed.outputs.any_changed == 'true'
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        ref: ${{ github.head_ref }}
    - name: Setup python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Build
      run: |
        python3 -m pip install -r .script/requirements.txt
        python3 -m pip install lib/metric-config-parser
    - name: Authenticate to GCP
      uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
      id: auth
      with:
        workload_identity_provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_DRYRUN_SERVICE_ACCOUNT_EMAIL }}
        token_format: id_token
        id_token_audience: https://us-central1-moz-fx-data-shared-prod.cloudfunctions.net/bigquery-etl-dryrun
        id_token_include_email: true
    - name: Export ID Token for Python
      run: echo "GOOGLE_GHA_ID_TOKEN=${{ steps.auth.outputs.id_token }}" >> $GITHUB_ENV
    - name: Validate Looker config files
      run: |
        echo "Run validation on changed files: "
        echo ${{ needs.changed.outputs.all_changed_files }}
        python3 .script/validate.py --config_repos='.' --config_repos=looker/ ${{ needs.changed.outputs.all_changed_files }}



