name: "Validate OpMon"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'opmon/**'
  push:
    branches:
      - main
    paths:
      - 'opmon/**'

jobs:
  changed:
    uses: ./.github/workflows/changed-files.yml
    with:
      path_filter: |
        opmon/**/*.toml
        opmon/**/*.toml.example

  validate-opmon:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/moz-fx-data-experiments/opmon:latest
    needs: changed
    if: needs.changed.outputs.any_changed == 'true'
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Validate OpMon config files
      run: |
        echo "Run validation on changed files: "
        echo ${{ needs.changed.outputs.all_changed_files }}
        opmon validate_config --config_repos='.' --config_repos=opmon/ ${{ needs.changed.outputs.all_changed_files }}



